name: Release

on:
  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  setup:
    runs-on: ubuntu-20.04
    outputs:
      DATE: ${{ steps.get_date.outputs.DATE }}
    steps:
      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  macos:
    strategy:
      matrix:
        python-version: ["3.8"]

    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.2.0"

      

      - name: Check Python version
        run: |
          python --version

      
      - name: install pip dependencies
        run: |
              python3 -m pip install -r requirements.txt
        

      - name: build
        run: |
              python3 -m PyInstaller --onefile UniversalTorchUpscaler.py
      
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: dist

  windows:
    strategy:
      matrix:
        python-version: ["3.8"]

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"


      

      - name: Check Python version
        run: |
          python --version

      
      - name: install pip dependencies
        run: |
              python3 -m pip install -r requirements.txt
        

      - name: build
        run: |
              python3 -m PyInstaller --onefile UniversalTorchUpscaler.py
      
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: dist

    

  linux:
    strategy:
      matrix:
        python-version: ["3.8"]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"



      - name: Check Python version
        run: |
          python --version

      
      - name: install pip dependencies
        run: |
              python3 -m pip install -r requirements.txt
        

      - name: build
        run: |
              python3 -m PyInstaller --onefile UniversalTorchUpscaler.py
      
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: dist
          
  Release:
    needs: [setup, macos, windows, linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: asset

      - name: dist
        run: |
          mkdir dist
          cp asset/artifact/* dist
          cd dist && ls

      
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ needs.setup.outputs.DATE }}
          tag_name: ${{ needs.setup.outputs.DATE }}
          body: Auto Release.
          draft: false
          prerelease: false
          files: dist/*
